language: node_js

node_js:
  - 10.15.3

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version

install:
  - yarn install --frozen-lockfile

script:
  - yarn build:prod
  - yarn test

after_success:
  - yarn test:send-coverage-to-coveralls
