language: node_js

node_js:
  - 8.15.1

cache: npm

before_install:
  - if [[ "$(npm -v)" != "$(npm v npm dist-tags.latest)" ]]; then npm i -g npm@latest; fi

before_script:
  - npm run bootstrap

script:
  - npm run test
